name: Setup Go

on:
  push:
    branches:
      - main
      - master
      - Version-v*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  setup-go-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5.2.0
        with:
          go-version: '1.16'
          check-latest: true
          cache: true
