name: Setup Go Environment

on:
  push:
    branches:
      - main
      - master
      - Version-v*

jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5.2.0
        with:
          go-version: '1.16'
          check-latest: true
          cache: true
