name: Setup Go

on: [push, pull_request]

jobs:
  setup-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5.2.0
        with:
          go-version: '1.17'
          check-latest: true
          cache: true
          architecture: x64
